# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("POEFilterUpdater")
        MainWindow.setEnabled(True)
        MainWindow.resize(520, 420)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(520, 420))
        MainWindow.setMaximumSize(QtCore.QSize(520, 420))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Select_label = QtWidgets.QLabel(self.centralwidget)
        self.Select_label.setGeometry(QtCore.QRect(70, 15, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Select_label.setFont(font)
        self.Select_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Select_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.Select_label.setObjectName("Select_label")
        self.SelectList = QtWidgets.QListWidget(self.centralwidget)
        self.SelectList.setGeometry(QtCore.QRect(10, 50, 201, 251))
        self.SelectList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SelectList.setObjectName("SelectList")
        self.UniquesCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.UniquesCheck.setEnabled(False)
        self.UniquesCheck.setGeometry(QtCore.QRect(20, 60, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.UniquesCheck.setFont(font)
        self.UniquesCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.UniquesCheck.setChecked(True)
        self.UniquesCheck.setObjectName("UniquesCheck")
        self.FragmentsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.FragmentsCheck.setEnabled(False)
        self.FragmentsCheck.setGeometry(QtCore.QRect(20, 110, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FragmentsCheck.setFont(font)
        self.FragmentsCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.FragmentsCheck.setChecked(True)
        self.FragmentsCheck.setObjectName("FragmentsCheck")
        self.DivinationCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.DivinationCheck.setEnabled(False)
        self.DivinationCheck.setGeometry(QtCore.QRect(20, 135, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DivinationCheck.setFont(font)
        self.DivinationCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.DivinationCheck.setChecked(True)
        self.DivinationCheck.setObjectName("DivinationCheck")
        self.FossilsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.FossilsCheck.setEnabled(False)
        self.FossilsCheck.setGeometry(QtCore.QRect(20, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FossilsCheck.setFont(font)
        self.FossilsCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.FossilsCheck.setChecked(True)
        self.FossilsCheck.setObjectName("FossilsCheck")
        self.ScarabsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.ScarabsCheck.setEnabled(False)
        self.ScarabsCheck.setGeometry(QtCore.QRect(20, 210, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ScarabsCheck.setFont(font)
        self.ScarabsCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ScarabsCheck.setChecked(True)
        self.ScarabsCheck.setObjectName("ScarabsCheck")
        self.ResonatorsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.ResonatorsCheck.setEnabled(False)
        self.ResonatorsCheck.setGeometry(QtCore.QRect(20, 185, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ResonatorsCheck.setFont(font)
        self.ResonatorsCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ResonatorsCheck.setChecked(True)
        self.ResonatorsCheck.setObjectName("ResonatorsCheck")
        self.IncubatorsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.IncubatorsCheck.setEnabled(False)
        self.IncubatorsCheck.setGeometry(QtCore.QRect(20, 260, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.IncubatorsCheck.setFont(font)
        self.IncubatorsCheck.setAcceptDrops(False)
        self.IncubatorsCheck.setAutoFillBackground(False)
        self.IncubatorsCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.IncubatorsCheck.setChecked(True)
        self.IncubatorsCheck.setTristate(False)
        self.IncubatorsCheck.setObjectName("IncubatorsCheck")
        self.OilsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.OilsCheck.setEnabled(False)
        self.OilsCheck.setGeometry(QtCore.QRect(20, 235, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OilsCheck.setFont(font)
        self.OilsCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.OilsCheck.setChecked(True)
        self.OilsCheck.setObjectName("OilsCheck")
        self.FilterName_label = QtWidgets.QLabel(self.centralwidget)
        self.FilterName_label.setGeometry(QtCore.QRect(230, 130, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.FilterName_label.setFont(font)
        self.FilterName_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.FilterName_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.FilterName_label.setObjectName("FilterName_label")
        self.League_label = QtWidgets.QLabel(self.centralwidget)
        self.League_label.setGeometry(QtCore.QRect(230, 170, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.League_label.setFont(font)
        self.League_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.League_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.League_label.setObjectName("League_label")
        self.OpenFilter_label = QtWidgets.QLabel(self.centralwidget)
        self.OpenFilter_label.setGeometry(QtCore.QRect(230, 50, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.OpenFilter_label.setFont(font)
        self.OpenFilter_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OpenFilter_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.OpenFilter_label.setObjectName("OpenFilter_label")
        self.SaveFilter_label = QtWidgets.QLabel(self.centralwidget)
        self.SaveFilter_label.setGeometry(QtCore.QRect(230, 310, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.SaveFilter_label.setFont(font)
        self.SaveFilter_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SaveFilter_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SaveFilter_label.setObjectName("SaveFilter_label")
        self.OverrideCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.OverrideCheck.setEnabled(False)
        self.OverrideCheck.setGeometry(QtCore.QRect(230, 350, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OverrideCheck.setFont(font)
        self.OverrideCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.OverrideCheck.setObjectName("OverrideCheck")
        self.OpenFileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.OpenFileBtn.setGeometry(QtCore.QRect(380, 50, 90, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.OpenFileBtn.setFont(font)
        self.OpenFileBtn.setStyleSheet("background-color: rgb(171, 171, 171);")
        self.OpenFileBtn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.OpenFileBtn.setObjectName("OpenFileBtn")
        self.SortBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SortBtn.setEnabled(False)
        self.SortBtn.setGeometry(QtCore.QRect(380, 230, 90, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SortBtn.setFont(font)
        self.SortBtn.setMouseTracking(False)
        self.SortBtn.setToolTip("")
        self.SortBtn.setAutoFillBackground(False)
        self.SortBtn.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.SortBtn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SortBtn.setCheckable(False)
        self.SortBtn.setAutoDefault(False)
        self.SortBtn.setDefault(False)
        self.SortBtn.setFlat(False)
        self.SortBtn.setObjectName("SortBtn")
        self.SaveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SaveBtn.setEnabled(False)
        self.SaveBtn.setGeometry(QtCore.QRect(380, 310, 90, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SaveBtn.setFont(font)
        self.SaveBtn.setStyleSheet("background-color: rgb(171, 171, 171);")
        self.SaveBtn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SaveBtn.setObjectName("SaveBtn")
        self.Changes_label = QtWidgets.QLabel(self.centralwidget)
        self.Changes_label.setGeometry(QtCore.QRect(600, 15, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Changes_label.setFont(font)
        self.Changes_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Changes_label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.Changes_label.setObjectName("Changes_label")
        self.Changes_list = QtWidgets.QListWidget(self.centralwidget)
        self.Changes_list.setGeometry(QtCore.QRect(540, 50, 201, 311))
        self.Changes_list.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.Changes_list.setObjectName("Changes_list")
        self.SelectAllBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SelectAllBtn.setEnabled(False)
        self.SelectAllBtn.setGeometry(QtCore.QRect(40, 315, 131, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SelectAllBtn.setFont(font)
        self.SelectAllBtn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SelectAllBtn.setObjectName("SelectAllBtn")
        self.RemoveAllBtn = QtWidgets.QPushButton(self.centralwidget)
        self.RemoveAllBtn.setEnabled(False)
        self.RemoveAllBtn.setGeometry(QtCore.QRect(40, 350, 131, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RemoveAllBtn.setFont(font)
        self.RemoveAllBtn.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.RemoveAllBtn.setObjectName("RemoveAllBtn")
        self.League = QtWidgets.QComboBox(self.centralwidget)
        self.League.setEnabled(False)
        self.League.setGeometry(QtCore.QRect(380, 170, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.League.setFont(font)
        self.League.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.League.setObjectName("League")
        self.League.addItem("")
        self.League.addItem("")
        self.League.addItem("")
        self.League.addItem("")
        self.FilterName = QtWidgets.QTextBrowser(self.centralwidget)
        self.FilterName.setGeometry(QtCore.QRect(350, 127, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FilterName.setFont(font)
        self.FilterName.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.FilterName.setObjectName("FilterName")
        self.UniqueMapsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.UniqueMapsCheck.setEnabled(False)
        self.UniqueMapsCheck.setGeometry(QtCore.QRect(20, 85, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.UniqueMapsCheck.setFont(font)
        self.UniqueMapsCheck.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.UniqueMapsCheck.setChecked(True)
        self.UniqueMapsCheck.setObjectName("UniqueMapsCheck")
        self.League_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.League_label_2.setGeometry(QtCore.QRect(230, 230, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.League_label_2.setFont(font)
        self.League_label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.League_label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.League_label_2.setObjectName("League_label_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(400, 370, 121, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.SelectList.raise_()
        self.Select_label.raise_()
        self.UniquesCheck.raise_()
        self.FragmentsCheck.raise_()
        self.DivinationCheck.raise_()
        self.FossilsCheck.raise_()
        self.ScarabsCheck.raise_()
        self.ResonatorsCheck.raise_()
        self.IncubatorsCheck.raise_()
        self.OilsCheck.raise_()
        self.FilterName_label.raise_()
        self.League_label.raise_()
        self.OpenFilter_label.raise_()
        self.SaveFilter_label.raise_()
        self.OverrideCheck.raise_()
        self.OpenFileBtn.raise_()
        self.SortBtn.raise_()
        self.SaveBtn.raise_()
        self.Changes_label.raise_()
        self.Changes_list.raise_()
        self.SelectAllBtn.raise_()
        self.RemoveAllBtn.raise_()
        self.League.raise_()
        self.FilterName.raise_()
        self.UniqueMapsCheck.raise_()
        self.League_label_2.raise_()
        self.progressBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 21))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMain.addAction(self.actionExit)
        self.menubar.addAction(self.menuMain.menuAction())
        self.Select_label.setBuddy(self.SelectList)
        self.FilterName_label.setBuddy(self.FilterName)
        self.League_label.setBuddy(self.League)
        self.Changes_label.setBuddy(self.Changes_list)
        self.League_label_2.setBuddy(self.League)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.FilterName, self.League)
        MainWindow.setTabOrder(self.League, self.OpenFileBtn)
        MainWindow.setTabOrder(self.OpenFileBtn, self.SortBtn)
        MainWindow.setTabOrder(self.SortBtn, self.SaveBtn)
        MainWindow.setTabOrder(self.SaveBtn, self.OverrideCheck)
        MainWindow.setTabOrder(self.OverrideCheck, self.SelectList)
        MainWindow.setTabOrder(self.SelectList, self.UniquesCheck)
        MainWindow.setTabOrder(self.UniquesCheck, self.UniqueMapsCheck)
        MainWindow.setTabOrder(self.UniqueMapsCheck, self.FragmentsCheck)
        MainWindow.setTabOrder(self.FragmentsCheck, self.DivinationCheck)
        MainWindow.setTabOrder(self.DivinationCheck, self.FossilsCheck)
        MainWindow.setTabOrder(self.FossilsCheck, self.ResonatorsCheck)
        MainWindow.setTabOrder(self.ResonatorsCheck, self.ScarabsCheck)
        MainWindow.setTabOrder(self.ScarabsCheck, self.OilsCheck)
        MainWindow.setTabOrder(self.OilsCheck, self.IncubatorsCheck)
        MainWindow.setTabOrder(self.IncubatorsCheck, self.SelectAllBtn)
        MainWindow.setTabOrder(self.SelectAllBtn, self.RemoveAllBtn)
        MainWindow.setTabOrder(self.RemoveAllBtn, self.Changes_list)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("POEFilterUpdater", "POEFilterUpdater"))
        self.Select_label.setText(_translate("POEFilterUpdater", "Select"))
        self.UniquesCheck.setText(_translate("POEFilterUpdater", "Uniques"))
        self.FragmentsCheck.setText(_translate("POEFilterUpdater", "Fragments"))
        self.DivinationCheck.setText(_translate("POEFilterUpdater", "Divination Cards"))
        self.FossilsCheck.setText(_translate("POEFilterUpdater", "Fossils"))
        self.ScarabsCheck.setText(_translate("POEFilterUpdater", "Scarabs"))
        self.ResonatorsCheck.setText(_translate("POEFilterUpdater", "Resonators"))
        self.IncubatorsCheck.setText(_translate("POEFilterUpdater", "Incubators"))
        self.OilsCheck.setText(_translate("POEFilterUpdater", "Oils"))
        self.FilterName_label.setText(_translate("POEFilterUpdater", "Filter Name:"))
        self.League_label.setText(_translate("POEFilterUpdater", "Choose league:"))
        self.OpenFilter_label.setText(_translate("POEFilterUpdater", "Open .filter file"))
        self.SaveFilter_label.setText(_translate("POEFilterUpdater", "Save .filter file"))
        self.OverrideCheck.setText(_translate("POEFilterUpdater", "Override .filter file"))
        self.OpenFileBtn.setText(_translate("POEFilterUpdater", "Open File"))
        self.SortBtn.setText(_translate("POEFilterUpdater", "Sort"))
        self.SaveBtn.setText(_translate("POEFilterUpdater", "Save"))
        self.Changes_label.setText(_translate("POEFilterUpdater", "Changes"))
        self.SelectAllBtn.setText(_translate("POEFilterUpdater", "Select All"))
        self.RemoveAllBtn.setText(_translate("POEFilterUpdater", "Remove All"))
        self.League.setItemText(0, _translate("POEFilterUpdater", "Current SC"))
        self.League.setItemText(1, _translate("POEFilterUpdater", "Current HC"))
        self.League.setItemText(2, _translate("POEFilterUpdater", "Standart SC"))
        self.League.setItemText(3, _translate("POEFilterUpdater", "Standart HC"))
        self.FilterName.setHtml(_translate("POEFilterUpdater", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.UniqueMapsCheck.setText(_translate("POEFilterUpdater", "Unique Maps"))
        self.League_label_2.setText(_translate("POEFilterUpdater", "Sort items:"))
        self.menuMain.setTitle(_translate("POEFilterUpdater", "Main"))
        self.actionExit.setText(_translate("POEFilterUpdater", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
